version: '3.8'

volumes:
  vol-emqx-data:
    name: iot-emqx-data
  #vol-emqx-etc:
  #  name: iot-emqx-etc
  vol-emqx-log:
    name: iot-emqx-log

services:

  node: 
    container_name: node
    image: "node:14"
    #restart: always
    working_dir: /home/node/app
    volumes:
      - ./mycode/index.js:/home/node/app/index.js
    ports:
      - "3000:3000"
      - "3001:3001"
      - "80:3002"
    link:
      - emqx
      - mongo
    command: sh -c "node index.js"

  mongo:
    container_name: my-mongo
    image: mongo:4.4
    #restart: always
    environment:
      TZ: "${TZ}" # Time Zone
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - ${MONGO_EXTERNAL_PORT}:27017
    volumes:
      - ./mongoDataIot:/data/db

  emqx:
    container_name: my-emqx
    image: emqx/emqx:4.2.3
    #restart: always
    ports:
      - 18083:18083 # dashboard port -> http://localhost:18083/#/
      #- 18084:18084 # secure dashboard (ssl)
      - 1883:1883
      - 8883:8883
      - 8083:8083 # websocket
      #- 8084:8084 # secure websocket
      - 8085:8081 # emqx api
    volumes:
      - vol-emqx-data:/opt/emqx/data # container data
      #- vol-emqx-etc:/opt/emqx/etc # emqx config, vars setted bellow, so its not necessary
      - vol-emqx-log:/opt/emqx/log # log files
    links:
      - mongo
    extra_hosts: # for webhooks communication, use this only when running locally! ipconfig /all > ipv4. This IP influence status of EMQX Resources.
      - "localhost:192.168.15.89" # casa
      #- "localhost:192.168.43.27" # hotspot celular
    environment: # change variables defined at \opt\emqx\etc\emqx.conf
      EMQX_NAME: iot
      EMQX_HOST: 127.0.0.1
      TZ: "${TZ}" # Time Zone
      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo" # Plugins to start
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "${EMQX_DASHBOARD__DEFAULT_USER__PASSWORD}" # DEFAULT DASH PASS
      EMQX_MANAGEMENT__DEFAULT__APPLICATION__SECRET: "${EMQX_MANAGEMENT__DEFAULT__APPLICATION__SECRET}" # emqx app secret
      EMQX_ALLOW_ANONYMOUS: "false" # avoid login without credentials
      EMQX_NOMATCH: "deny" # ACL
      EMQX_AUTH__MONGO__TYPE: single # MONGO CONNECTION (uses plugin emqx_auth_mongo)
      EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
      EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0
      EMQX_AUTH__MONGO__SERVER: "mongo:${MONGO_EXTERNAL_PORT}"
      EMQX_AUTH__MONGO__POOL: 8
      EMQX_AUTH__MONGO__LOGIN: "${MONGO_INITDB_ROOT_USERNAME}"
      EMQX_AUTH__MONGO__PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin
      EMQX_AUTH__MONGO__DATABASE: "my-iot-db"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules" # used by GET /brokerauth
      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser" # boolean field on document for user role
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__SUPER_QUERY: "off"
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password" # field on document for password
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"
      EMQX_AUTH__MONGO__ACL_QUERY: "on" # Access control list, ACL query
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules" # GET /brokerauth
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"
